{
 "title": "CI data",
 "time": { "from": "2019-01-29T19:46:11.433Z", "to": "2019-01-29T21:26:16.206Z" },
 "panels": [
  {
   "title": "Kubelet and node exporter availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\".*9100\"}",
     "legendFormat": "{{ instance }} node exporter"
    },
    {
     "expr": "up{instance=~\".*10250\"}",
     "legendFormat": "{{ instance }} kubelet"
    }
   ]
  },
  {
   "title": "kubelet_running_container_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_container_count"
    }
   ]
  },
  {
   "title": "kubelet_pleg_relist_latency_microseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "clockms" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{quantile='0.5'}"
    }
   ]
  },
  {
   "title": "kubelet_pleg_relist_interval_microseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "clockms" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_interval_microseconds{quantile='0.5'}"
    }
   ]
  },
  {
   "title": "kubelet_cgroup_manager_latency_microseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "clockms" }
   ],
   "targets": [
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{quantile='0.5'}"
    }
   ]
  },
  {
   "title": "kubelet_runtime_operations_errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_errors",
     "legendFormat": "{{ instance }} {{ operation_type }}"
    }
   ]
  },
  {
   "title": "kubelet_runtime_operations rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kubelet_runtime_operations[1m])",
     "legendFormat": "{{ instance }} {{ operation_type }}"
    }
   ]
  },
  {
   "title": "kubelet_runtime_operations_latency_microseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "clockms" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{quantile=\"0.5\"}",
     "legendFormat": "{{ instance }} {{ operation_type }}"
    }
   ]
  }
 ]
}