{
 "title": "Kube ApiServer",
 "time": { "from": "2019-01-31T05:21:47.262Z", "to": "2019-01-31T06:32:10.725Z" },
 "panels": [
  {
   "title": "Up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{namespace=~\".*api.*\"}",
     "legendFormat": "{{ namespace }} {{ pod }}"
    }
   ]
  },
  {
   "title": "aggregator_unavailable_apiservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aggregator_unavailable_apiservice_count",
     "legendFormat": "{{ name }} {{ reason }}"
    }
   ]
  },
  {
   "title": "KubeApiserverOperator_queue_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "KubeApiserverOperator_queue_latency",
     "legendFormat": "queue {{ quantile }} latency"
    }
   ]
  },
  {
   "title": "APIServiceOpenAPIAggregationControllerQueue1_queue_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "APIServiceOpenAPIAggregationControllerQueue1_queue_latency{quantile=\"0.5\",service!=\"api\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "apiserver_audit_event_total rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(apiserver_audit_event_total[1m]) > 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "KubeApiserverOperator_work_duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "KubeApiserverOperator_work_duration",
     "legendFormat": "work duration {{ quantile }} latency"
    }
   ]
  },
  {
   "title": "claims_work_duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "claims_work_duration{namespace=\"openshift-kube-controller-manager\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "KubeApiserverOperator_adds and retries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(KubeApiserverOperator_adds[1m])",
     "legendFormat": "adds rate"
    },
    { "expr": "KubeApiserverOperator_retries", "legendFormat": "retries" }
   ]
  },
  {
   "title": "cluster_quantile:scheduler_binding_latency:histogram_quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cluster_quantile:scheduler_binding_latency:histogram_quantile",
     "legendFormat": "binding {{ quantile }}"
    }
   ]
  },
  {
   "title": "KubeSchedulerClient_queue_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "KubeSchedulerClient_queue_latency",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "scheduler_total_preemption_attempts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_total_preemption_attempts",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "scheduler_pod_preemption_victims",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_pod_preemption_victims",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "apiserver_registered_watchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_registered_watchers > 0"
    }
   ]
  },
  {
   "title": "apiserver_current_inflight_requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests{requestKind=\"mutating\"} > 0",
     "legendFormat": "{{ instance }} mutating"
    }
   ]
  }
 ]
}