{
 "title": "Kubelet",
 "time": { "from": "2019-01-31T05:13:50.769Z", "to": "2019-01-31T06:46:09.230Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kubelet up status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "up{node=\"$node\"}",
     "legendFormat": "{{ node }} up"
    }
   ]
  },
  {
   "title": "Node Ready errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_condition{status=\"unknown\",condition=\"Ready\",node=\"$node\"}==1",
     "legendFormat": "{{ node }} unknown Ready"
    },
    {
     "expr": "kube_node_status_condition{status=\"false\",condition=\"Ready\",node=\"$node\"}==1",
     "legendFormat": "{{ node }} not Ready"
    },
    {
     "expr": "kube_node_status_condition{status=\"true\",condition=\"DiskPressure\",node=\"$node\"}==1",
     "legendFormat": "{{ node }} DiskPressure"
    },
    {
     "expr": "kube_node_status_condition{status=\"true\",condition=\"OutOfDisk\",node=\"$node\"}==1",
     "legendFormat": "{{ node }} PIDPressure"
    },
    {
     "expr": "kube_node_status_condition{status=\"true\",condition=\"MemoryPressure\",node=\"$node\"}==1",
     "legendFormat": "{{ node }} OutOfDisk"
    }
   ]
  },
  {
   "title": "kubelet_pleg_relist_latency_microseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{node=\"$node\"}",
     "legendFormat": "{{ quantile }} quantile"
    }
   ]
  },
  {
   "title": "kubelet_pleg_relist_interval_microseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_interval_microseconds{node=\"$node\"}",
     "legendFormat": "{{ quantile }} quantile"
    }
   ]
  },
  {
   "title": "kubelet_cgroup_manager_latency_microseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{quantile='0.5',node=\"$node\"}",
     "legendFormat": "{{ operation_type }}"
    }
   ]
  },
  {
   "title": "Number of containers per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_container_count{node=\"$node\"}",
     "legendFormat": "containers per node"
    }
   ]
  },
  {
   "title": "kubelet_runtime_operations rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kubelet_runtime_operations{node=\"$node\"}[1m])",
     "legendFormat": "{{ operation_type }}"
    }
   ]
  },
  {
   "title": "kubelet_runtime_operations_latency_microseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{node=\"$node\", quantile=\"0.5\"}",
     "legendFormat": "{{ operation_type }}"
    }
   ]
  },
  {
   "title": "kubelet_runtime_operations_errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_errors{node=\"$node\"}",
     "legendFormat": "{{ operation_type }}"
    }
   ]
  }
 ]
}