{
 "title": "Namespace details",
 "time": { "from": "2019-01-31T05:19:20.816Z", "to": "2019-01-31T06:45:33.060Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespaces",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU use time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "namespace:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Namespace memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "namespace:container_memory_usage_bytes:sum{namespace=\"$namespace\"}",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pod Phases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\"}==1",
     "legendFormat": "{{ pod }} {{ phase }}"
    }
   ]
  },
  {
   "title": "Container Statuses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\"} > 0",
     "legendFormat": "{{ pod }} {{ container }} {{ reason }}"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0",
     "legendFormat": "{{ pod }} {{ container }} restart"
    },
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }} {{ container }} {{ reason }}"
    },
    {
     "expr": "kube_pod_container_status_terminated_reason{namespace=\"$namespace\"} > 0",
     "legendFormat": "{{ pod }} {{ container }} {{ reason }}"
    }
   ]
  }
 ]
}