{
 "title": "Networking",
 "time": { "from": "2019-01-31T05:15:30.336Z", "to": "2019-01-31T06:36:24.269Z" },
 "panels": [
  {
   "title": "container_network_receive_bytes_total eth0 rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{interface=\"eth0\"}[1m]) > 0",
     "legendFormat": "{{ node }} {{ interface }}"
    }
   ]
  },
  {
   "title": "container_network_transmit_bytes_total eth0 irate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{interface=\"eth0\"}[1m]) > 0",
     "legendFormat": "{{ node }} {{ interface }}"
    }
   ]
  },
  {
   "title": "node_network_receive_bytes_total tun0 rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"tun0\"}[1m]) > 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "node_network_transmit_bytes_total tun0 rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"tun0\"}[1m]) > 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Receive errors and dropped packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_errors_total[1m]) > 0",
     "legendFormat": "Error {{ namespace }} {{ name }} {{ interface }}"
    },
    {
     "expr": "irate(container_network_receive_packets_dropped_total[1m]) > 0",
     "legendFormat": "Drop {{ namespace }} {{ name }} {{ interface }}"
    }
   ]
  },
  {
   "title": "Transmit errors and dropped packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_errors_total[1m]) > 0",
     "legendFormat": "Errors {{ instance }} {{ interface }}"
    },
    {
     "expr": "irate(container_network_transmit_packets_dropped_total[1m]) > 0",
     "legendFormat": "Drops {{ instance }} {{ interface }}"
    }
   ]
  },
  {
   "title": "etcd_network_client_grpc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_network_client_grpc_received_bytes_total"
    },
    {
     "expr": "etcd_network_client_grpc_sent_bytes_total"
    }
   ]
  },
  {
   "title": "node_network_carrier erros",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_network_carrier != 1",
     "legendFormat": "{{ namespace }} {{ pod }} {{ interface }}"
    }
   ]
  }
 ]
}