{
 "title": "Node-exporter",
 "time": { "from": "2019-01-31T05:19:15.555Z", "to": "2019-01-31T06:32:20.740Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(node_load1, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "load 1"
    },
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "load 5"
    },
    {
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "load 15"
    }
   ]
  },
  {
   "title": "Pod Evictions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_collector_evictions_number != 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "node_nf_conntrack_entries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "node_arp_entries rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_arp_entries{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "node_disk_read_bytes_total rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "node_disk_reads_completed_total rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "node_disk_written_bytes_total rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "node_disk_writes_completed_total rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "node_context_switches_total irate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "node_disk_io_now",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{instance=\"$instance\"} > 0",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}