{
 "title": "Pod info",
 "time": { "from": "2019-01-29T19:39:32.726Z", "to": "2019-01-29T21:34:05.453Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Terminated reason",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", pod=\"$pod\"}==1"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Phases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\", pod=\"$pod\"}==1",
     "legendFormat": "{{ phase }} "
    },
    {
     "expr": "kube_pod_status_ready{namespace=\"$namespace\", pod=\"$pod\"}==1",
     "legendFormat": "Ready"
    },
    {
     "expr": "kube_pod_status_scheduled{namespace=\"$namespace\", pod=\"$pod\"}==1",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "restarts"
    },
    { "legendFormat": "Running" },
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\"}==1",
     "legendFormat": "{{ reason }}"
    }
   ]
  }
 ]
}