{
 "title": "Volumes",
 "time": { "from": "2019-01-31T05:25:45.756Z", "to": "2019-01-31T06:28:12.819Z" },
 "panels": [
  {
   "title": "volume_operation avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volume_operation_total_seconds_sum{plugin_name=\"kubernetes.io/aws-ebs\"} / volume_operation_total_seconds_count{plugin_name=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "{{ operation_name }}"
    }
   ]
  },
  {
   "title": "volume_operation avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_operation_duration_seconds_sum{volume_plugin=\"kubernetes.io/aws-ebs\"} / storage_operation_duration_seconds_count{volume_plugin=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "{{ operation_name }}"
    }
   ]
  },
  {
   "title": "volume_provision ebs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_operation_duration_seconds_bucket{operation_name=\"volume_provision\", volume_plugin=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "volume_mount ebs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_operation_duration_seconds_bucket{operation_name=\"volume_mount\", volume_plugin=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "volume_attach ebs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_operation_duration_seconds_bucket{operation_name=\"volume_attach\", volume_plugin=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "volume_detach ebs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_operation_duration_seconds_bucket{operation_name=\"volume_detach\", volume_plugin=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "volume_unmount ebs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_operation_duration_seconds_bucket{operation_name=\"volume_unmount\", volume_plugin=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "volume_delete ebs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_operation_duration_seconds_bucket{operation_name=\"volume_delete\", volume_plugin=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "volume_operation_total_seconds_bucket provision",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volume_operation_total_seconds_bucket{operation_name=\"provision\", plugin_name=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "delete {{ le }}"
    }
   ]
  },
  {
   "title": "volume_operation_total_seconds_bucket delete",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volume_operation_total_seconds_bucket{operation_name=\"delete\", plugin_name=\"kubernetes.io/aws-ebs\"}",
     "legendFormat": "delete {{ le }}"
    }
   ]
  }
 ]
}